CR EQU 13 ;RETORNO DE ACARREO, ESCRIBE CADENA
LF EQU 10 ;SALTO DE LINEA, MOSTRAR REGISTROS DE PALETA 

DATOS SEGMENT ; DEFINIR EL TEXTO A MOSTRAR
    LINEA1 DB CR,LF,'FRANCISCO DANIEL GREGORIO GUEVARA',CR,LF,'$'
    LINEA2 DB 'TECNOLOGICO DE STUDIOS SUPERIORES DE JILOTEPEC',CR,LF,'$'
    LINEA3 DB 'ING.SISTEMAS COMPUTACIONALES',CR,LF,'$'
    LINEA4 DB '3502 ;-;',CR,LF,'$'
    
DATOS ENDS  ;FIN DEL TEXTO A MOSTRAR

PILA SEGMENT STACK ;INICIALIZACION DE LA PILA

    DB 64 DUP('PILA')
    
PILA ENDS  ;FIN DE PILA

CODIGO SEGMENT ;INICIO DEL PROGRAMA

    LN PROC FAR ;INICIAR EL PROCESO LN
    
    ASSUME CS:CODIGO,DS:DATOS,SS:PILA ;
    MOV AX,DATOS   ;DIRECCION DEL SEGMENTO DE DATOS
    MOV DS,AX      ;INDICAR EL SEGMENTO DE DATOS
    LEA DX,LINEA1  ;DIRECCION DEL MENSAJE
    CALL ESCRIBE   ;LLAMAR AL PROCESO 
    LEA DX,LINEA2  ;DIRECCION DEL MENSAJE
    CALL ESCRIBE   ;LLAMAR AL PROCESO 
    LEA DX,LINEA3  ;DIRECCION DEL MENSAJE
    CALL ESCRIBE   ;LLAMAR AL PROCESO 
    LEA DX,LINEA4  ;DIRECCION DEL MENSAJE
    CALL ESCRIBE   ;LLAMAR AL PROCE-----------~~~SO 
    MOV AX,4C00H   ;FUNCION PARA TERMINAR EL PROGRAMA
    INT 21H        ;LLAMAR A LA INTERRUPCION 21
    
    LN ENDP       ;TERMINAR EL PROCESO LN
    
    ESCRIBE PROC  ;INICIAR EL PROCESO ESCRIBE
    MOV AH,9      ;ESCRIBIR TEXTO EN PANTALLA
    INT 21H       ;LLAMAR A LA INTERRUPCION
    RET           ;RETORNAR 
    ESCRIBE ENDP  ;FIN DEL ?ROCESO ESCRIBE
    
CODIGO ENDS   ;FIN DEL PROGRAMA

END LN   ;CERRAR EL PROCESO LN